version: "3.3"

services:
  cms_test_db:
    container_name: cms_test_db
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  cms_test:
    container_name: cms_test
    build:
      context: .
      target: worker
    depends_on:
      - "cms_test_db"
    environment:
      CMS_CONFIG: /usr/local/etc/cms-testdb.conf
      # Could be removed in the future, see:
      # - https://github.com/pytest-dev/pytest/issues/7443
      # - https://github.com/actions/runner/issues/241
      PYTEST_ADDOPTS: --color=yes
    volumes:
      - "./codecov:/home/cmsuser/cms/codecov"
    privileged: true
    # disable coverage testing. it seems to be broken with our Dockerfile.
    # possibly an issue with the new ubuntu? or with our hacky python setup
    command: >
      wait-for-it cms_test_db:5432 -- sh -c "
      sed 's|/cmsuser:your_password_here@localhost:5432/cmsdb|/postgres@cms_test_db:5432/cmsdbfortesting|' ./config/cms.conf.sample | sudo tee /usr/local/etc/cms-testdb.conf ;
      . venv/bin/activate ;
      pip install -r dev-requirements.txt ;
      dropdb --host=cms_test_db --username=postgres cmsdbfortesting ;
      createdb --host=cms_test_db --username=postgres cmsdbfortesting ;
      cmsInitDB ;
      pytest . ;
      dropdb --host=cms_test_db --username=postgres cmsdbfortesting ;
      createdb --host=cms_test_db --username=postgres cmsdbfortesting ;
      cmsInitDB ;
      cmsRunFunctionalTests -v ;
      "
