name: ci

on:
  push:
    branches: [eio, eio-prod]


jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        base_image: ["ubuntu:noble"]

    steps:
      - uses: actions/checkout@v2

      - name: Check available cgroups
        run: |
          mount | grep cgroup

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Build and push docker image
        run: |
          if [ "$GITHUB_REF_NAME" = "eio-prod" ]; then
            TAGNAME=prod
          else
            TAGNAME=test
          fi
          docker buildx build --load --push -t ghcr.io/e-i-o/cms:$TAGNAME . \
              --cache-from type=registry,ref=ghcr.io/e-i-o/cms:build-cache \
              --cache-to type=registry,ref=ghcr.io/e-i-o/cms:build-cache \
              --build-arg BASE_IMAGE=${{ matrix.base_image }}
          docker tag ghcr.io/e-i-o/cms:$TAGNAME cms-testcms

      - name: Run tests
        run: |
          docker compose -p cms -f docker/docker-compose.test.yml run --rm testcms

